# Generated by Django 6.0.3 on 2026-05-20 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MethaneStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Zapravka nomi')),
                ('address', models.TextField(verbose_name='Manzili')),
                ('latitude', models.FloatField(verbose_name='Kenglik (Latitude)')),
                ('longitude', models.FloatField(verbose_name='Uzunlik (Longitude)')),
                ('status', models.CharField(choices=[('GREEN', '🟢 Yashil (1-5 ta mashina)'), ('YELLOW', '🟡 Sariq (6-15 ta mashina)'), ('RED', '🔴 Qizil (15+ mashina)'), ('BLACK', '⚫ Yopiq / Ishlamayapti'), ('WHITE', "⚪ Ma'lumot yo'q")], default='WHITE', max_length=10, verbose_name='Navbat holati')),
                ('has_power', models.BooleanField(default=True, verbose_name='Elektr energiyasi (Svet)')),
                ('gas_pressure', models.CharField(choices=[('HIGH', 'Yaxshi (Normal)'), ('LOW', 'Past (Bosim kam)'), ('NONE', "Bosim yo'q (Gaz yo'q)")], default='HIGH', max_length=10, verbose_name='Gaz bosimi')),
                ('price', models.IntegerField(default=3800, verbose_name="1 m³ gaz narxi (so'm)")),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aloqa telefoni')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan stansiya')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Metan Zapravka',
                'verbose_name_plural': 'Metan Zapravkalar',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='StationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Taqdim etilgan zapravka nomi')),
                ('address', models.TextField(verbose_name='Manzili')),
                ('latitude', models.FloatField(verbose_name='Kenglik (Latitude)')),
                ('longitude', models.FloatField(verbose_name='Uzunlik (Longitude)')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aloqa raqami')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('is_processed', models.BooleanField(default=False, verbose_name="Ko'rib chiqildi")),
            ],
            options={
                'verbose_name': 'Yangi Zapravka Arizasi',
                'verbose_name_plural': 'Yangi Zapravka Arizalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StationWorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='monitoring.methanestation', verbose_name='Ish joyi (Zapravka)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kassir Profili',
                'verbose_name_plural': 'Kassirlar Profillari',
            },
        ),
    ]
